[package]
name = "twilight-redis"
version = "0.1.0"
edition = "2021"

[features]
default = ["bb8", "validation"]
bb8 = ["dep:bb8-redis"]
deadpool = ["dep:deadpool-redis"]
validation = ["dep:bytecheck", "rkyv/validation"]

[dependencies]
bb8-redis = { version = "0.13", default-features = false, optional = true }
bytecheck = { version = "0.7", default-features = false, optional = true }
deadpool-redis = { version = "0.12", default-features = false, optional = true, features = ["rt_tokio_1"]}
itoa = { version = "1.0", default-features = false }
rkyv = { version = "0.7", default-features = false, features = ["size_32", "std", "strict"] }
thiserror = { version = "1.0", default-features = false }
twilight-model = { version = "0.15", default-features = false }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }